package com.casino.casinoservice.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/*
 * this is the representation if a bet order, if the user lucky number is the same random number generated by casino number
 * customer will win the double of the bet amount 
 * if it is less or more by one customer will win the half of the bet amount
 * otherwise he will lose the bet
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class GambleOrder {
    
    private int customerId;

    private String customerName;

    private double betAmount;

    private int luckyNumber;

    private double customerBalance;

}